## HSS Parameters
hss:  
  # Transport Type. "TCP" and "SCTP" are valid options.
  # Note: SCTP works but is still experimental. TCP has been load-tested and performs in a production environment.
  transport: "TCP"
  #IP Addresses to bind on (List) - For TCP only the first IP is used, for SCTP all used for Transport (Multihomed).
  bind_ip: ["172.24.0.13"]
  #bind_ip: ["0.0.0.0"]

  #Port to listen on (Same for TCP & SCTP)
  bind_port: 3868

  #Value to populate as the OriginHost in Diameter responses
  OriginHost: "hss.epc.mnc001.mcc001.3gppnetwork.org"

  #Value to populate as the OriginRealm in Diameter responses
  OriginRealm: "epc.mnc001.mcc001.3gppnetwork.org"

  #Value to populate as the Product name in Diameter responses
  ProductName: "pyHSS"

  #Name of the Site, shown in API
  site_name: "LibreCellular"

  #Your Home Mobile Country Code (Used for PLMN calcluation)
  MCC: "001"
  #Your Home Mobile Network Code (Used for PLMN calcluation)
  MNC: "01"

  #Enable GMLC / SLh Interface
  SLh_enabled: False

  #IMSI of Test Subscriber for Unit Checks (Optional)
  test_sub_imsi: '001021234567890'

  #The maximum time to wait, in seconds, before disconnecting a client when no data is received.
  client_socket_timeout: 120

  #The maximum time to wait, in seconds, before disconnecting a client when no data is received.
  client_socket_timeout: 300

  #The maximum time to wait, in seconds, before discarding a diameter request.
  diameter_request_timeout: 3

  #The amount of time, in seconds, before purging a disconnected client from the Active Diameter Peers key in redis.
  active_diameter_peers_timeout: 10

  #Prevent updates from being performed without a valid 'Provisioning-Key' in the header
  lock_provisioning: False

  #Provisioning Key for this HSS, alias for an API key. Required to be present in the header of requests to this HSS' api, if lock_provisioning is True.
  provisioning_key: "changeThisKeyInProduction"

  #If enabled sends CLRs to old MME when new MME attaches active sub
  CancelLocationRequest_Enabled: False

  #Workaround for some MMEs to force an Insert Subscriber Data request to be sent immediately after ULA
  Insert_Subscriber_Data_Force: False

  #Default Initial Filter Criteria for IMS Subscribers
  #Jinja Formatted Template, see the example for variables passed to it.
  Default_iFC: 'default_ifc.xml'

  #Default Sh User Data
  Default_Sh_UserData: 'default_sh_user_data.xml'

  #S-CSCF Pool
  scscf_pool:
    - 'sip:scscf.ims.mnc001.mcc001.3gppnetwork.org:6060'

  roaming:
    outbound:
      # Whether or not to a subscriber to connect to an undefined network when outbound roaming.
      allow_undefined_networks: True

  # SCTP Socket Parameters
  sctp:
    rtoMax: 5000
    rtoMin: 500
    rtoInitial: 1000

api:
  page_size: 200
  # Whether or not to return key-based data when querying the AUC. Disable in production systems.
  enable_insecure_auc: True

benchmarking:
  # Whether to enable benchmark logging
  enabled: True
  # How often to report, in seconds. Not all benchmarking supports interval reporting.
  reporting_interval: 3600

eir:
  imsi_imei_logging: True    #Store current IMEI / IMSI pair in backend
  no_match_response: 2       #Greylist
  # Define an optional TAC csv file path
  #tac_database_csv: '/etc/pyhss/tac_database.csv'

logging:
  level: INFO
  logfiles:
    hss_logging_file: /pyhss/log/pyhss_hss.log
    diameter_logging_file: /pyhss/log/pyhss_diameter.log
    geored_logging_file: /pyhss/log/pyhss_geored.log
    metric_logging_file: /pyhss/log/pyhss_metrics.log
  sqlalchemy_sql_echo: True
  sqlalchemy_pool_recycle: 15
  sqlalchemy_pool_size: 30
  sqlalchemy_max_overflow: 0

## Database Parameters
database:
  db_type: mysql    #Supported types are MySQL and Postgres
  server: 172.24.0.11
  #server: 127.0.0.1
  username: pyhss
  password: pyhsspasswd
  database: hss

## External Webhook Notifications
webhooks:
  enabled: False
  endpoints:
    - 'http://127.0.0.1:8181'

## Geographic Redundancy Parameters
geored:
  enabled: False
  sync_actions: ['HSS', 'IMS', 'PCRF', 'EIR']    #What event actions should be synced
  endpoints:                         #List of PyHSS API Endpoints to update
    - 'http://hss01.mnc001.mcc001.3gppnetwork.org:8080'
    - 'http://hss02.mnc001.mcc001.3gppnetwork.org:8080'

#Redis is required to run PyHSS. An instance running on a local network is recommended for production.
redis:
  # Which connection type to attempt. Valid options are: tcp, unix, sentinel
  # tcp - Connection via a standard TCP socket to a given host and port.
  # unix - Connect to redis via a unix socket, provided by unixSocketPath.
  # sentinel - Connect to one or more redis sentinel hosts.
  connectionType: "tcp"
  host: 172.24.0.12
  #host: localhost
  port: 6379

prometheus:
  enabled: False
  port: 8081    #If the API is run the API runs on the next port number up from this
  async_subscriber_count: False    #If enabled the subscriber count will be updated asynchronously for Prometheus

snmp:
  port: 1161
  listen_address: 172.24.0.13
  #listen_address: 127.0.0.1
